# fly.toml app configuration file generated for puskesmas-backend-api on 2025-08-12T01:30:40+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'puskesmas-backend-api'
primary_region = 'sin'

[build]
  dockerfile = './Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 750

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
